<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PhieuNhapXuatNguyenLieuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('phieu_nhap_xuat_nguyen_lieus')->insert([
            //1 
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000001',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 455000,
                'tong_tien'           => 2275000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //1 CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000001',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 455000,
                'tong_tien'           => 2275000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //2 NL  2 
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000002',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 1900,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 20088,
                'tong_tien'           => 100440,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //2 NL  2 CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000002',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 1900,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 20088,
                'tong_tien'           => 100440,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //3 NL  3 
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000003',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 37638,
                'tong_tien'           => 188190,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //3 NL  3 CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000003',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 37638,
                'tong_tien'           => 188190,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //4 NL  4 
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000004',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 37638,
                'tong_tien'           => 188190,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //4 NL  4 - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000004',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 37638,
                'tong_tien'           => 188190,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //5 NL  5 
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000005',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 37638,
                'tong_tien'           => 188190,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //5 NL  5 
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000005',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 37638,
                'tong_tien'           => 188190,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //6 NL  6 
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000006',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 30000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 145000,
                'tong_tien'           => 725000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //6 NL  6 
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000006',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 30000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 145000,
                'tong_tien'           => 725000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //7 NL 7
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000007',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Túi',
                'gia_tien'            => 65000,
                'tong_tien'           => 325000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //7 NL 7 - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000007',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Túi',
                'gia_tien'            => 65000,
                'tong_tien'           => 325000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //8 NL 8
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000008',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 4535,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 80000,
                'tong_tien'           => 400000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //8 NL 8 - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000008',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 4535,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 80000,
                'tong_tien'           => 400000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //9 NL 9
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000009',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 5,
                'dinh_luong'          => 2500,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Túi',
                'gia_tien'            => 105000,
                'tong_tien'           => 525000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //9 NL 9 - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000009',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 5,
                'dinh_luong'          => 2500,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Túi',
                'gia_tien'            => 105000,
                'tong_tien'           => 525000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //10 NL 10 ĐÀO NGÂM RHODES
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000010',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 2400,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 65000,
                'tong_tien'           => 325000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //10 NL 10 ĐÀO NGÂM RHODES - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000010',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 2400,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Hộp',
                'gia_tien'            => 65000,
                'tong_tien'           => 325000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //11 NL 11 VẢI NGÂM THÁI
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000011',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 1150,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 51000,
                'tong_tien'           => 25000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //11 NL 11 VẢI NGÂM THÁI - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000011',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 1150,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 51000,
                'tong_tien'           => 25000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //12 NL 12 SIRO MAULIN TÁO (APPLE)
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000012',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 11250,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 200000,
                'tong_tien'           => 1000000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
             //12 NL 12 SIRO MAULIN TÁO (APPLE) - CH 2
             [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000012',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 11250,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 200000,
                'tong_tien'           => 1000000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //13 NL 13 SIRO MAULIN XOÀI
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000013',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 65000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 205000,
                'tong_tien'           => 1025000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //13 NL 13 SIRO MAULIN XOÀI - CH 2
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000013',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(90),
                'so_luong'            => 5,
                'dinh_luong'          => 65000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Chai',
                'gia_tien'            => 205000,
                'tong_tien'           => 1025000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //14 NL 14 LY NHỰA PET NẮP CẦU 350ML/ THÙNG (1000 LY)	1.020.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000014',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 1020000,
                'tong_tien'           => 5100000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //14 CH 2 NL 14 LY NHỰA PET NẮP CẦU 350ML/ THÙNG (1000 LY)	1.020.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000014',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 1020000,
                'tong_tien'           => 5100000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //15 NL 15LY NHỰA PET NẮP CẦU 500ML/ THÙNG (1000 LY)	1.070.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000015',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 1070000,
                'tong_tien'           => 5350000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            
            //15 CH 2 NL 15LY NHỰA PET NẮP CẦU 500ML/ THÙNG (1000 LY)	1.070.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000015',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 1070000,
                'tong_tien'           => 5350000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //16 NL 16 LY NHỰA PET NẮP CẦU 700ML/ THÙNG (1000 LY)	1.400.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000016',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 1400000,
                'tong_tien'           => 7000000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //16 CH 2 NL 16 LY NHỰA PET NẮP CẦU 700ML/ THÙNG (1000 LY)	1.400.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000016',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 1400000,
                'tong_tien'           => 7000000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //17 NL 17 Ly giấy 12oz - 360ml	753.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000017',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 753000,
                'tong_tien'           => 3765000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //17 CH 2 NL 17 Ly giấy 12oz - 360ml	753.000 ₫	Thùng 1000ly
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000017',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(900),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 753000,
                'tong_tien'           => 3765000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //18 NL 18 Cà phê rang PHA MÁY gói 1000G 430.000 đ
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000018',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(30),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 430000,
                'tong_tien'           => 2150000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //18 CH 2 NL 18 Cà phê rang PHA MÁY gói 1000G 430.000 đ
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000018',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(30),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 5,
                'dinh_luong'          => 5000,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 430000,
                'tong_tien'           => 2150000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //19 NL 19 Cà Phê Hòa Tan 3 trong 1 (50 gói)
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000019',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 10,
                'dinh_luong'          => 500,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 179000,
                'tong_tien'           => 1790000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //19 CH 2 NL 19 Cà Phê Hòa Tan 3 trong 1 (50 gói)
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000019',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 10,
                'dinh_luong'          => 500,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 179000,
                'tong_tien'           => 1790000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //20 NL 20 Cà Phê Hòa Tan 3 trong 1 (20 gói)
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000020',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 10,
                'dinh_luong'          => 200,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 75000,
                'tong_tien'           => 750000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //20 CH 2 NL 20 Cà Phê Hòa Tan 3 trong 1 (20 gói)
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000020',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 10,
                'dinh_luong'          => 200,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 75000,
                'tong_tien'           => 750000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],

            //21 NL 21  Trà lài hộp giấy 150g
            [
                'ma_cua_hang'         => 'CH00000001',
                'ma_nguyen_lieu'      => 'NL00000021',
                'ma_nhan_vien'        => 'NV00000003',
                'so_lo'               => 'LO00000001',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 10,
                'dinh_luong'          => 750,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 75000,
                'tong_tien'           => 750000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            //21  CH 2 NL 21  Trà lài hộp giấy 150g
            [
                'ma_cua_hang'         => 'CH00000002',
                'ma_nguyen_lieu'      => 'NL00000021',
                'ma_nhan_vien'        => 'NV00000004',
                'so_lo'               => 'LO00000002',
                'loai_phieu'          => 0, 
                'ngay_san_xuat'       => Carbon::now()->subDays(10),
                'han_su_dung'         => Carbon::now()->addDays(600),
                'so_luong'            => 10,
                'dinh_luong'          => 750,
                'so_luong_ton_truoc'  => 0,
                'don_vi'              => 'Thùng',
                'gia_tien'            => 75000,
                'tong_tien'           => 750000,
                'ngay_tao_phieu'      => Carbon::now(),
                'ghi_chu'             => 'Nhập hàng đầu tiên',
                'created_at'          => Carbon::now(),
                'updated_at'          => Carbon::now(),
            ],
            // Thêm dòng khác nếu cần
        ]);
    }
}
